# Generated by Django 5.0.6 on 2024-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_insufficientstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insufficientstock',
            name='quantity_needed',
            field=models.IntegerField(null=True),
        ),
    ]
