name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.x']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r application/requirements.txt

  deploy-s3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: application
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_LEXISID }}
          aws-secret-access-key: ${{ secrets.AWS_LEXISKEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync ./application s3://bucket-hackathon-lexisnexis --delete
